baseURL = "https://me.jowj.net/"
title = "josiah's blog"
languageCode = "en-us"

[markup]
enableEmoji = true

[markup.highlight]
codeFences = true
guessSyntax = false
tabWidth = 4
style = "monokai"   # or another style you prefer
lineNos = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
hardWraps = false # Changed from the previous suggestion

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
