#+TITLE: big bend trip
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+AUTHOR: josiah

* family vacations, planning
its pretty hard to make a family vacation work. in our case, we've got 5 adult children who are all partnered up, 2 of those groups had new children, and our parents take care of their parents so time away is expensive. we've made some half-assed attempts at family trips before, but nothing terribly succesful. as a result, none of us have really traveled all that much together.

this year my elder brother @mrled <#revisit> decide it was really important to us to /do something/ with the year, something we'd be proud of and glad to have done after it was over. 2020 was a rough year for everyone of course, and we wanted to make sure that 2021 didn't end up looking just the same as its predecessor.
  
we talked off and on for the past year about going on a trip together and where we might go. it didn't become a reality until October sometime, when we actually started requesting PTO and looking at destinations.

we did decide relatively early on thbat we'd like to camp. we camped a lot as a kid, though i'm not sure either of us actually enjoyed most of those camping trips. we figured we'd try again as adults who could self direct a bit more. we looked at availability at several national parks, including the grand canyon and big bend national park, but with susch short notice there was nothing available. my partner L had worked a few interpretting jobs at Big Bend Ranch /state/ park, and recommended we check it out. she warned us that it was more remote than the national park, but it did have availability, so we booked a 3 day stay there. we were taking a week off, so we booked another 3 day stay in Marfa after our big bend trip was over; the idea was we'd camp pretty remote / without ameneities, then go stay in a nice AirBNB and have nice food every day.

* packing and we also thought it
Since this was actually two trips in one it was really hard to figure out what to bring! we both brought /so much bullshit/ lmao. the absolute best things we brought were our two bikes and 3 different water storage things. as a reaction to the shitshow that was the Febuary winter storm in Texas <#revisit>, mrled had started preparing some basics like potable water storage. He bought 2 10 liter jugs, and this trip was their trial run. I brought a collapsable 2.5 gallon water jug, and we mostly used this as our water source, filling it from the 10 liter ones.

the car eventually got /utterly/ packed. i've never filled a car so thoroughly before. part of what made this trip a bit hard to pack intelligently for was that it was actually two trips in one; 3 days in Big Bend followed by 3 days in Marfa. Both of us bought a bunch of bullshit from REI, we prepped as well as we could. I bought two new car ties, got a rotation and an alignment. The day before we left both of us are still packing, trying to get all out shit together.

* travelling out there.
That first day of traveling was really nice. I drove to mrled's, we loaded up his stuff and his bike, said goodbye to A and Milo, a very sad dog. I drove us through Fredricksburg, where we stopped and had lunch at a diner that was Pretty Alright. I drove a bit further until we hit around the halfway mark, where I swapped with Micah at a gas station. I neglected to fill up on gas there, and we almost didn't make it to the next gas station. Got there chuffing, running on fumes.

Eventually me made it to Alpine, where we had an AirBNB for a night so we could head into BBR with a bit more daylight. We got to the place, unloaded our shit, and ate a decent dinner at a bad restaurant; no beer, bad service, right on the main road. The menu was standard mexican food, with some sea food additions that we avoided, Alpine being very far from water. We walked home, stopping at a liquor store to stock up on whiskey and beer for Big Bend, and we sat together in the AirBNB drinking and cracking jokes. I can't remember what he said that really got me, but with hours left in the night I got hiccups from some joke he made and I never recovered the rest of the night.

The next day we loaded up, got in the car, I started driving, and the car was /pulling/, I mean bad. Not an auspicious start to the day. mrled mentioned that it was pulling for him the evening before, but this seemed much worse. we go to a gas station and we even out all the tires. its a bit better, but its still pulling real fucking hard. we called every mechanic within driving distance, but it was Sunday and these towns are small so no one was open. we eventually decided to soldier on to BBR, knowing that we might lose a day to car trouble / getting towed, which felt better than DEFINITELY losing a day to car trouble / waiting for a shop to open.

* alpine to bbr, bbr day 1
  - that long, 20 or 30 miles of "road" in my lil civic
  - impressions of how beautiful, how quiet it is
  - check in at the ranger station
  - first camp, grilled cheese, bacon, potato soup

* day 2 in BBR
  - long morning before we leave
  - the bike ride there, exploring
  - trailhead no water
  - run out of water
  - the way back
  - doing nothing but dinner

* day 3 in bbr
  - long morning
  - revenge ourselves on the trailhead
  - actually making it
  - god the view was incredible
  - still cutting it close on the water thing!
  - second hike in the evening instead  of doing nothing!

* day 4 in bbr, leaving, marfa day 1
  - leaving the park, a bigger adventure than arriving
  - ramming speeds to go up hills
  - finally get out of the park, still some weird pull now that we're going >20 miles per hour
  - no one will work on my car in presidio, keep going
  - make it to Marfa, car starts to pull a lot less
  - call TEN fucking mechanics, no one can help me.
  - spend the day chilling, showering, doing laundry, being clean.
  - /weird/ moon ritual thing
  - fancy dinner

* marfa day 2
  - donald judd muesem was awesome
  - the Other Marfa museum was less awesome.
  - dinner at @water stop,
  - spent a lot of time just sitting together and playing video games

* marfa day 3
  - we weren't sure if we needed this day originally
  - we decided to keep it and go to balmorhea state park, but since the car was acting weird we decided to just stay local
  - biked around the town, stopping into stores. micah bought some stuff
  - most of the day just ended up being metroid dread together and chill. I loved it.
  - fancy dinner again.

* marfa -> austin
  - actually an uneventful trip! we loaded everything up the night before, woke up and rolled out.
  - long trip. car wasn't pulling anywhere near as hard as it had before
  - really dunno what happend!

* retrospective
  - god get a higher clearance vehicle, at minimum
  - consider a 4x4.
  - grab much more portable water than we had. my little 2.5 gal thing was a life saver and was almost not enough! nalgenes?
  - marfa didn't need so much time. i'd probably go again in enough years, but by far the coolest thing was the donald judd museum
