#+TITLE: big bend trip
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+AUTHOR: josiah

* family vacations, planning
its pretty hard to make a family vacation work. in our case, we've got 5 adult children who are all partnered up, 2 of those groups had new children, and our parents take care of their parents so time away is expensive. we've made some half-assed attempts at family trips before, but nothing terribly succesful. as a result, none of us have really traveled all that much together.

** finally planning
this year my elder brother @mrled <#revisit, should be Micah text, @mrled twitter link I guess> decided it was really important to us to /do something/ with the year, something we'd be proud of and glad to have done after it was over. 2020 was a rough year for everyone of course, and we wanted to make sure that 2021 didn't end up looking just the same as its predecessor.
  
we talked off and on for the past year about going on a trip together and where we might go. it didn't become a reality until October sometime, when we actually started requesting PTO and looking at destinations.

we did decide relatively early on that we'd like to camp. we camped a lot as a kid, though i'm not sure either of us actually enjoyed most of those camping trips. we figured we'd try again as adults who could self direct a bit more. we looked at availability for several national parks, including the grand canyon and big bend national park, but with such short notice there was nothing available. my partner L had worked a few interpretting jobs at Big Bend Ranch /state/ park, and recommended we check it out. she warned us that it was more remote than the national park, but it did have availability, so we booked a 3 day stay there. we were taking a week off, so we booked another 3 day stay in Marfa after our big bend trip was over; the idea was we'd camp pretty remote / without ameneities, then go stay in a nice AirBNB and have nice food every day.

** packing
Since this was actually two trips in one it was really hard to figure out what to bring! we both brought /so much bullshit/ lmao. the absolute best things we brought were our two bikes and 3 different water storage things. as a reaction to the shitshow that was the Febuary winter storm in Texas <#revisit>, Micah had started preparing some basics like potable water storage. He bought 2 10 liter jugs, and this trip was their trial run. I brought a collapsable 2.5 gallon water jug, and we mostly used this as our water source, filling it from the 10 liter ones.

the car eventually got /utterly/ packed. i've never filled a car so thoroughly before. Both of us bought a bunch of bullshit from REI, we prepped as well as we could. I bought two new car tires, got a rotation and an alignment. The day before we left both of us are still packing, trying to get all out shit together.

* the way there
** austin -> alpine
 That first day of traveling was really nice. I said goobye to L, drove to Micah's, we loaded up his stuff and his bike, said goodbye to A. I drove us through Fredricksburg, where we stopped and had lunch at a diner that was Pretty Alright. I drove a bit further until we hit around the halfway mark, where I swapped with Micah at a gas station. I neglected to fill up on gas there, and we almost didn't make it to the next gas station. Got there chuffing, running on fumes.

 Eventually me made it to Alpine, where we had an AirBNB for a night so we could head into BBR with a bit more daylight. We got to the place, unloaded our shit, and walked to find food. we ate a decent dinner at a bad restaurant; no beer, bad service, right on the main road. Pretty good food. The menu was standard mexican fare, with some sea food additions that we avoided, Alpine being very far from water. We walked back to the airbnb, stopping at a liquor store to stock up on whiskey and beer for Big Bend, and we sat together in the AirBNB drinking and cracking jokes. I can't remember what he said that really got me, but early on I got hiccups from some joke he made and I never recovered the rest of the night.

** alpine to bbr, bbr day 1
 The next day we loaded up, got in the car, I started driving, and the car was /pulling/, I mean bad. Not an auspicious start to the day. Micah mentioned that it was pulling for him the evening before, but this seemed much worse. we go to a gas station and we even out all the tires. its a bit better, but its still pulling real fucking hard. we called every mechanic within driving distance, but it was Sunday and these towns are small so no one was open. we eventually decided to soldier on to BBR, knowing that we might lose a day to car trouble / getting towed, which felt better than DEFINITELY losing a day to car trouble / waiting for a shop to open.

 alpine to presidio, the nearest town to BBR state park, is not very far, about an hour and a half. presidio to BBR is ALSO not very far, just like 30 miles to the entrance of the park, but after that you've another 27 miles to go over the most unmaintained road i've ever had the displeasure of driving my little civic on. absolutely deranged to even allow 2wd vehicles on this road. It takes us hours, and it takes at least half that time for me to get comfortable driving offroad. We stopped once at an overlook, just above a little desert valley. It was the first time we'd exited the car since presidio. It was utterly silent. I have lived in a city my whole life, and though i've camped a bit as a child I don't really remember much of it. This level of silence was astonishing.

 eventually we made it to the ranger station, a place with power / wifi in air quotes, and a little store that you could buy a few things if you forgot them (or didn't realize you needed them); some blankets, headlamps, coffee cups, trailfood, etc. We checked in, got some guidance on what trails to check out, then headed out to our drive up campsite. We stayed in <#place, check with micah>, a collection of campgrounds that were all empty. we were so surprised! we had the whole place to ourselves for the duration of our stay.

 #+html: <br>
 #+begin_box
 we asked why the park seemed so empty on our way out on Wednesday, and the lady at the ranger station blinked and said "this is the busiest we've been in months."
 #+end_box

 we made camp, for the first time as adults, pitching tents and blowing up sleeping pads and trying to figure out what the fuck the instructions were telling us to do. we settled in and made a fire to cook dinner: bacon grilled cheese sandwhiches and potato soup. I think it was the best meal we had all week, we toasted the bread in the bacon grease and i almost died at how good it was.

 we sat at the fire as the sun set and the moon rose. that first night was a few days before full moon, and we could see /everything/ with no light. we were a little bummed we couldn't see the milky way, supposedly you can see it in BBR since its part of the national dark sky project <#link here>, but seeing the desert by full moonlight was also incredible. pictures just don't capture any of the magic.

 <insert picture>

* in big brend ranch
** day 2 in BBR and The Big Mistake
 we started the day at a fairly normal time, between 7 and 8, but it took a long while for us to really get going. we made coffee in a french press by boiling potable water in the one cooking dish i brought, a dutch oven; we made a breakfast of eggs and bacon in the same dish; we cleaned up and +ran from+ heroically fought large mean wasps who were interested in our bacon. finally, around 10 or 10:30 we get on bikes and decide to ride to the ranger station and get some advice.

 #+html: <br>
 #+begin_box
 readers who have been to the desert before might notice that this is a bit late in the day to get started.
 #+end_box

 the route to the ranger station is ~1 mile from our camp ground but by the time we get there we're a bit out of breath -- we traveled back to the station via the same road we drove in on, a road in name only. the ranger at the station gave us some maps, we picked a route, and set off again on our steeds

 <insert picture of steeds>

 #+html: <br>
 #+begin_box
 before this account goes any further its worth pointing out: we are big idiots, and I specifically am the largest idiot. I knew better but am not used to overriding other people unless i'm really very sure, and my hesitency could've really hurt us!
 #+end_box

 because we are bad planners and didn't think too much about what we were doing, we had to go back the direction we came and then some just to get to the road that gets to the trailhead. we ride (bump, really) through a vague path for 3 miles before finally hitting the trailhead. as we arrive I run out of water. my brother still has half his nalgene left. the maps the ranger gave us show that the trail was only 2 miles long or so; we figure 40 minutes, maybe an hour, then we head back, and we can share the remaining water.

 oops.

 we continue on with our bikes on the trail and that was such a cool experience; neither of us had ever done trail riding before, and taking bikes up and down draws, jumping edges, and trying to just Stay On the Bike was so much fun. We drink more of the water as time goes on, and eventually we run out. I tell Micah I'm really nervous and want to head back, but he convinces me we're almost at the end and we would be upset if we didn't finish the trail! we give it another 10 minutes before I say I'm uncomfortable and we actually head back.

 the ride back down was rough; we're both exhausted, its well past 1 PM at this point. the sun is beating down on us. we reapply sun screen during a breather but what we really wish we had was /water/. the sand, fun and challenging on the way in, is a mire on the way out. when we finally make it to the trail head we rest in the shade of the compostable toilet building and dread the upcoming ride to camp.

 the ride to camp was excruciating. neither of us have had water for several hours, and its well past the time we should've eaten lunch. we're both shakey and slow, trying our best to stay on our bikes whenever the road turns from sharp rocks to loose sand, both of us aware that we /really/ erred getting to this point.

 finally, past 3 PM, I see the turn off to our campsite. Micah's a ways behind me. I turn in, go down the hill, and stumble off my bike to get water and food. we sit there, mostly silent, filling our bottles from the main jugs we brought in and eating a mix of suger foods and whatever we could find that didn't require cooking. the first words we say to each other are about how there was a while there we thought we might have needed SAR.

 we do nothing else the whole day. we cook dinner but I couldn't tell you what we made. I recall it being good, but not as good as the grilled cheese from the night before. we go to bed early.

** day 3 in bbr
   - long morning
   - revenge ourselves on the trailhead
   - actually making it
   - god the view was incredible
   - still cutting it close on the water thing!
   - second hike in the evening instead  of doing nothing!

* transition day: leaving the park, arriving in marfa

  - leaving the park, a bigger adventure than arriving
  - ramming speeds to go up hills
  - finally get out of the park, still some weird pull now that we're going >20 miles per hour
  - no one will work on my car in presidio, keep going
  - make it to Marfa, car starts to pull a lot less
  - call TEN fucking mechanics, no one can help me.
  - spend the day chilling, showering, doing laundry, being clean.
  - /weird/ moon ritual thing
  - fancy dinner

* marfa
** marfa day 2
   - donald judd muesem was awesome
   - the Other Marfa museum was less awesome.
   - dinner at @water stop,
   - spent a lot of time just sitting together and playing video games

** marfa day 3
   - we weren't sure if we needed this day originally
   - we decided to keep it and go to balmorhea state park, but since the car was acting weird we decided to just stay local
   - biked around the town, stopping into stores. micah bought some stuff
   - most of the day just ended up being metroid dread together and chill. I loved it.
   - fancy dinner again.

* the way home
  - actually an uneventful trip! we loaded everything up the night before, woke up and rolled out.
  - long trip. car wasn't pulling anywhere near as hard as it had before
  - really dunno what happend!

* retrospective
  - god get a higher clearance vehicle, at minimum
  - consider a 4x4.
  - grab much more portable water than we had. my little 2.5 gal thing was a life saver and was almost not enough! nalgenes?
  - marfa didn't need so much time. i'd probably go again in enough years, but by far the coolest thing was the donald judd museum
